-- DuckLake Silver Schema (Generated from PostgreSQL silver_hot)
-- Compatible with Parquet storage - no PRIMARY KEY/UNIQUE/NOT NULL/DEFAULT constraints
-- Auto-generated: 2026-01-01

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.account_signers_snapshot (
    account_id VARCHAR,
    signer VARCHAR,
    ledger_sequence BIGINT,
    closed_at TIMESTAMP,
    weight INTEGER,
    sponsor VARCHAR,
    ledger_range BIGINT,
    era_id VARCHAR,
    version_label VARCHAR,
    valid_to TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.accounts_current (
    account_id VARCHAR,
    balance VARCHAR,
    sequence_number BIGINT,
    num_subentries INTEGER,
    num_sponsoring INTEGER,
    num_sponsored INTEGER,
    home_domain VARCHAR,
    master_weight INTEGER,
    low_threshold INTEGER,
    med_threshold INTEGER,
    high_threshold INTEGER,
    flags INTEGER,
    auth_required BOOLEAN,
    auth_revocable BOOLEAN,
    auth_immutable BOOLEAN,
    auth_clawback_enabled BOOLEAN,
    signers VARCHAR,
    sponsor_account VARCHAR,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    last_modified_ledger BIGINT,
    ledger_range BIGINT,
    era_id VARCHAR,
    version_label VARCHAR
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.accounts_snapshot (
    account_id VARCHAR,
    ledger_sequence BIGINT,
    closed_at TIMESTAMP,
    balance VARCHAR,
    sequence_number BIGINT,
    num_subentries INTEGER,
    num_sponsoring INTEGER,
    num_sponsored INTEGER,
    home_domain VARCHAR,
    master_weight INTEGER,
    low_threshold INTEGER,
    med_threshold INTEGER,
    high_threshold INTEGER,
    flags INTEGER,
    auth_required BOOLEAN,
    auth_revocable BOOLEAN,
    auth_immutable BOOLEAN,
    auth_clawback_enabled BOOLEAN,
    signers VARCHAR,
    sponsor_account VARCHAR,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    ledger_range BIGINT,
    era_id VARCHAR,
    version_label VARCHAR,
    valid_to TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.claimable_balances_current (
    balance_id VARCHAR,
    claimants VARCHAR,
    asset_type VARCHAR,
    asset_code VARCHAR,
    asset_issuer VARCHAR,
    asset VARCHAR,
    amount BIGINT,
    sponsor VARCHAR,
    flags INTEGER,
    last_modified_ledger BIGINT,
    ledger_sequence BIGINT,
    created_at TIMESTAMP,
    ledger_range BIGINT,
    inserted_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.claimable_balances_snapshot (
    balance_id VARCHAR,
    ledger_sequence BIGINT,
    asset_type VARCHAR,
    asset_code VARCHAR,
    asset_issuer VARCHAR,
    amount VARCHAR,
    claimants VARCHAR,
    flags INTEGER,
    sponsor_account VARCHAR,
    ledger_range BIGINT,
    era_id VARCHAR,
    version_label VARCHAR,
    valid_to TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.contract_data_current (
    contract_id VARCHAR,
    contract_key_type VARCHAR,
    contract_durability VARCHAR,
    asset VARCHAR,
    asset_code VARCHAR,
    asset_issuer VARCHAR,
    asset_type VARCHAR,
    balance_holder VARCHAR,
    contract_data_xdr VARCHAR,
    last_modified_ledger BIGINT,
    ledger_sequence BIGINT,
    created_at TIMESTAMP,
    ledger_range BIGINT,
    inserted_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.enriched_history_operations (
    transaction_hash VARCHAR,
    operation_index INTEGER,
    ledger_sequence BIGINT,
    source_account VARCHAR,
    type INTEGER,
    type_string VARCHAR,
    created_at TIMESTAMP,
    transaction_successful BOOLEAN,
    operation_result_code VARCHAR,
    operation_trace_code VARCHAR,
    ledger_range BIGINT,
    source_account_muxed VARCHAR,
    asset VARCHAR,
    asset_type VARCHAR,
    asset_code VARCHAR,
    asset_issuer VARCHAR,
    source_asset VARCHAR,
    source_asset_type VARCHAR,
    source_asset_code VARCHAR,
    source_asset_issuer VARCHAR,
    destination VARCHAR,
    destination_muxed VARCHAR,
    amount BIGINT,
    source_amount BIGINT,
    from_account VARCHAR,
    from_muxed VARCHAR,
    to_address VARCHAR,
    to_muxed VARCHAR,
    limit_amount BIGINT,
    offer_id BIGINT,
    selling_asset VARCHAR,
    selling_asset_type VARCHAR,
    selling_asset_code VARCHAR,
    selling_asset_issuer VARCHAR,
    buying_asset VARCHAR,
    buying_asset_type VARCHAR,
    buying_asset_code VARCHAR,
    buying_asset_issuer VARCHAR,
    price_n INTEGER,
    price_d INTEGER,
    price DECIMAL,
    starting_balance BIGINT,
    home_domain VARCHAR,
    inflation_dest VARCHAR,
    set_flags INTEGER,
    set_flags_s VARCHAR,
    clear_flags INTEGER,
    clear_flags_s VARCHAR,
    master_key_weight INTEGER,
    low_threshold INTEGER,
    med_threshold INTEGER,
    high_threshold INTEGER,
    signer_account_id VARCHAR,
    signer_key VARCHAR,
    signer_weight INTEGER,
    data_name VARCHAR,
    data_value VARCHAR,
    host_function_type VARCHAR,
    parameters VARCHAR,
    address VARCHAR,
    contract_id VARCHAR,
    function_name VARCHAR,
    balance_id VARCHAR,
    claimant VARCHAR,
    claimant_muxed VARCHAR,
    predicate VARCHAR,
    liquidity_pool_id VARCHAR,
    reserve_a_asset VARCHAR,
    reserve_a_amount BIGINT,
    reserve_b_asset VARCHAR,
    reserve_b_amount BIGINT,
    shares BIGINT,
    shares_received BIGINT,
    into_account VARCHAR,
    into_muxed VARCHAR,
    sponsor VARCHAR,
    sponsored_id VARCHAR,
    begin_sponsor VARCHAR,
    tx_successful BOOLEAN,
    tx_fee_charged BIGINT,
    tx_max_fee BIGINT,
    tx_operation_count INTEGER,
    tx_memo_type VARCHAR,
    tx_memo VARCHAR,
    ledger_closed_at TIMESTAMP,
    ledger_total_coins BIGINT,
    ledger_fee_pool BIGINT,
    ledger_base_fee INTEGER,
    ledger_base_reserve INTEGER,
    ledger_transaction_count INTEGER,
    ledger_operation_count INTEGER,
    ledger_successful_tx_count INTEGER,
    ledger_failed_tx_count INTEGER,
    is_payment_op BOOLEAN,
    is_soroban_op BOOLEAN,
    inserted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.enriched_history_operations_soroban (
    transaction_hash VARCHAR,
    operation_index INTEGER,
    ledger_sequence BIGINT,
    source_account VARCHAR,
    type INTEGER,
    type_string VARCHAR,
    created_at TIMESTAMP,
    transaction_successful BOOLEAN,
    operation_result_code VARCHAR,
    operation_trace_code VARCHAR,
    ledger_range BIGINT,
    source_account_muxed VARCHAR,
    asset VARCHAR,
    asset_type VARCHAR,
    asset_code VARCHAR,
    asset_issuer VARCHAR,
    source_asset VARCHAR,
    source_asset_type VARCHAR,
    source_asset_code VARCHAR,
    source_asset_issuer VARCHAR,
    destination VARCHAR,
    destination_muxed VARCHAR,
    amount BIGINT,
    source_amount BIGINT,
    from_account VARCHAR,
    from_muxed VARCHAR,
    to_address VARCHAR,
    to_muxed VARCHAR,
    limit_amount BIGINT,
    offer_id BIGINT,
    selling_asset VARCHAR,
    selling_asset_type VARCHAR,
    selling_asset_code VARCHAR,
    selling_asset_issuer VARCHAR,
    buying_asset VARCHAR,
    buying_asset_type VARCHAR,
    buying_asset_code VARCHAR,
    buying_asset_issuer VARCHAR,
    price_n INTEGER,
    price_d INTEGER,
    price DECIMAL,
    starting_balance BIGINT,
    home_domain VARCHAR,
    inflation_dest VARCHAR,
    set_flags INTEGER,
    set_flags_s VARCHAR,
    clear_flags INTEGER,
    clear_flags_s VARCHAR,
    master_key_weight INTEGER,
    low_threshold INTEGER,
    med_threshold INTEGER,
    high_threshold INTEGER,
    signer_account_id VARCHAR,
    signer_key VARCHAR,
    signer_weight INTEGER,
    data_name VARCHAR,
    data_value VARCHAR,
    host_function_type VARCHAR,
    parameters VARCHAR,
    address VARCHAR,
    contract_id VARCHAR,
    function_name VARCHAR,
    balance_id VARCHAR,
    claimant VARCHAR,
    claimant_muxed VARCHAR,
    predicate VARCHAR,
    liquidity_pool_id VARCHAR,
    reserve_a_asset VARCHAR,
    reserve_a_amount BIGINT,
    reserve_b_asset VARCHAR,
    reserve_b_amount BIGINT,
    shares BIGINT,
    shares_received BIGINT,
    into_account VARCHAR,
    into_muxed VARCHAR,
    sponsor VARCHAR,
    sponsored_id VARCHAR,
    begin_sponsor VARCHAR,
    tx_successful BOOLEAN,
    tx_fee_charged BIGINT,
    tx_max_fee BIGINT,
    tx_operation_count INTEGER,
    tx_memo_type VARCHAR,
    tx_memo VARCHAR,
    ledger_closed_at TIMESTAMP,
    ledger_total_coins BIGINT,
    ledger_fee_pool BIGINT,
    ledger_base_fee INTEGER,
    ledger_base_reserve INTEGER,
    ledger_transaction_count INTEGER,
    ledger_operation_count INTEGER,
    ledger_successful_tx_count INTEGER,
    ledger_failed_tx_count INTEGER,
    is_payment_op BOOLEAN,
    is_soroban_op BOOLEAN,
    inserted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.offers_current (
    offer_id BIGINT,
    seller_id VARCHAR,
    selling_asset_type VARCHAR,
    selling_asset_code VARCHAR,
    selling_asset_issuer VARCHAR,
    buying_asset_type VARCHAR,
    buying_asset_code VARCHAR,
    buying_asset_issuer VARCHAR,
    amount BIGINT,
    price_n INTEGER,
    price_d INTEGER,
    price DECIMAL,
    flags INTEGER,
    last_modified_ledger BIGINT,
    ledger_sequence BIGINT,
    created_at TIMESTAMP,
    sponsor VARCHAR,
    ledger_range BIGINT,
    inserted_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.offers_snapshot (
    offer_id BIGINT,
    seller_account VARCHAR,
    ledger_sequence BIGINT,
    closed_at TIMESTAMP,
    selling_asset_type VARCHAR,
    selling_asset_code VARCHAR,
    selling_asset_issuer VARCHAR,
    buying_asset_type VARCHAR,
    buying_asset_code VARCHAR,
    buying_asset_issuer VARCHAR,
    amount VARCHAR,
    price VARCHAR,
    flags INTEGER,
    created_at TIMESTAMP,
    ledger_range BIGINT,
    era_id VARCHAR,
    version_label VARCHAR,
    valid_to TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.token_transfers_raw (
    timestamp TIMESTAMP,
    transaction_hash VARCHAR,
    ledger_sequence BIGINT,
    source_type VARCHAR,
    from_account VARCHAR,
    to_account VARCHAR,
    asset_code VARCHAR,
    asset_issuer VARCHAR,
    amount BIGINT,
    token_contract_id VARCHAR,
    operation_type INTEGER,
    transaction_successful BOOLEAN,
    inserted_at TIMESTAMP,
    ledger_range BIGINT
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.trustlines_current (
    account_id VARCHAR,
    asset_type VARCHAR,
    asset_issuer VARCHAR,
    asset_code VARCHAR,
    liquidity_pool_id VARCHAR,
    balance BIGINT,
    trust_line_limit BIGINT,
    buying_liabilities BIGINT,
    selling_liabilities BIGINT,
    flags INTEGER,
    last_modified_ledger BIGINT,
    ledger_sequence BIGINT,
    created_at TIMESTAMP,
    sponsor VARCHAR,
    ledger_range BIGINT,
    inserted_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.trustlines_snapshot (
    account_id VARCHAR,
    asset_code VARCHAR,
    asset_issuer VARCHAR,
    asset_type VARCHAR,
    balance VARCHAR,
    trust_limit VARCHAR,
    buying_liabilities VARCHAR,
    selling_liabilities VARCHAR,
    authorized BOOLEAN,
    authorized_to_maintain_liabilities BOOLEAN,
    clawback_enabled BOOLEAN,
    ledger_sequence BIGINT,
    created_at TIMESTAMP,
    ledger_range BIGINT,
    era_id VARCHAR,
    version_label VARCHAR,
    valid_to TIMESTAMP
);

