-- DuckLake Silver Schema (Generated from PostgreSQL silver_hot)
-- Compatible with Parquet storage - no PRIMARY KEY/UNIQUE/NOT NULL/DEFAULT constraints
-- Auto-generated: 2026-01-01

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.account_signers_snapshot (
    account_id VARCHAR,
    signer VARCHAR,
    ledger_sequence BIGINT,
    closed_at TIMESTAMP,
    weight INTEGER,
    sponsor VARCHAR,
    ledger_range BIGINT,
    era_id VARCHAR,
    version_label VARCHAR,
    valid_to TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.accounts_current (
    account_id VARCHAR,
    balance VARCHAR,
    sequence_number BIGINT,
    num_subentries INTEGER,
    num_sponsoring INTEGER,
    num_sponsored INTEGER,
    home_domain VARCHAR,
    master_weight INTEGER,
    low_threshold INTEGER,
    med_threshold INTEGER,
    high_threshold INTEGER,
    flags INTEGER,
    auth_required BOOLEAN,
    auth_revocable BOOLEAN,
    auth_immutable BOOLEAN,
    auth_clawback_enabled BOOLEAN,
    signers VARCHAR,
    sponsor_account VARCHAR,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    last_modified_ledger BIGINT,
    ledger_range BIGINT,
    era_id VARCHAR,
    version_label VARCHAR
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.accounts_snapshot (
    account_id VARCHAR,
    ledger_sequence BIGINT,
    closed_at TIMESTAMP,
    balance VARCHAR,
    sequence_number BIGINT,
    num_subentries INTEGER,
    num_sponsoring INTEGER,
    num_sponsored INTEGER,
    home_domain VARCHAR,
    master_weight INTEGER,
    low_threshold INTEGER,
    med_threshold INTEGER,
    high_threshold INTEGER,
    flags INTEGER,
    auth_required BOOLEAN,
    auth_revocable BOOLEAN,
    auth_immutable BOOLEAN,
    auth_clawback_enabled BOOLEAN,
    signers VARCHAR,
    sponsor_account VARCHAR,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    ledger_range BIGINT,
    era_id VARCHAR,
    version_label VARCHAR,
    valid_to TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.claimable_balances_current (
    balance_id VARCHAR,
    claimants VARCHAR,
    asset_type VARCHAR,
    asset_code VARCHAR,
    asset_issuer VARCHAR,
    asset VARCHAR,
    amount BIGINT,
    sponsor VARCHAR,
    flags INTEGER,
    last_modified_ledger BIGINT,
    ledger_sequence BIGINT,
    created_at TIMESTAMP,
    ledger_range BIGINT,
    inserted_at TIMESTAMP,
    updated_at TIMESTAMP,
    claimants_count INTEGER,
    closed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.claimable_balances_snapshot (
    balance_id VARCHAR,
    ledger_sequence BIGINT,
    asset_type VARCHAR,
    asset_code VARCHAR,
    asset_issuer VARCHAR,
    amount VARCHAR,
    claimants VARCHAR,
    flags INTEGER,
    sponsor_account VARCHAR,
    ledger_range BIGINT,
    era_id VARCHAR,
    version_label VARCHAR,
    valid_to TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.contract_data_current (
    contract_id VARCHAR,
    key_hash VARCHAR,
    durability VARCHAR,
    asset_type VARCHAR,
    asset_code VARCHAR,
    asset_issuer VARCHAR,
    data_value VARCHAR,
    last_modified_ledger BIGINT,
    ledger_sequence BIGINT,
    closed_at TIMESTAMP,
    created_at TIMESTAMP,
    ledger_range BIGINT,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.token_registry (
    contract_id VARCHAR,
    token_name VARCHAR,
    token_symbol VARCHAR,
    token_decimals INTEGER,
    asset_code VARCHAR,
    asset_issuer VARCHAR,
    token_type VARCHAR,
    first_seen_ledger BIGINT,
    last_modified_ledger BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.enriched_history_operations (
    transaction_hash VARCHAR,
    operation_index INTEGER,
    ledger_sequence BIGINT,
    source_account VARCHAR,
    type INTEGER,
    type_string VARCHAR,
    created_at TIMESTAMP,
    transaction_successful BOOLEAN,
    operation_result_code VARCHAR,
    operation_trace_code VARCHAR,
    ledger_range BIGINT,
    source_account_muxed VARCHAR,
    asset VARCHAR,
    asset_type VARCHAR,
    asset_code VARCHAR,
    asset_issuer VARCHAR,
    source_asset VARCHAR,
    source_asset_type VARCHAR,
    source_asset_code VARCHAR,
    source_asset_issuer VARCHAR,
    destination VARCHAR,
    destination_muxed VARCHAR,
    amount BIGINT,
    source_amount BIGINT,
    from_account VARCHAR,
    from_muxed VARCHAR,
    to_address VARCHAR,
    to_muxed VARCHAR,
    limit_amount BIGINT,
    offer_id BIGINT,
    selling_asset VARCHAR,
    selling_asset_type VARCHAR,
    selling_asset_code VARCHAR,
    selling_asset_issuer VARCHAR,
    buying_asset VARCHAR,
    buying_asset_type VARCHAR,
    buying_asset_code VARCHAR,
    buying_asset_issuer VARCHAR,
    price_n INTEGER,
    price_d INTEGER,
    price DECIMAL,
    starting_balance BIGINT,
    home_domain VARCHAR,
    inflation_dest VARCHAR,
    set_flags INTEGER,
    set_flags_s VARCHAR,
    clear_flags INTEGER,
    clear_flags_s VARCHAR,
    master_key_weight INTEGER,
    low_threshold INTEGER,
    med_threshold INTEGER,
    high_threshold INTEGER,
    signer_account_id VARCHAR,
    signer_key VARCHAR,
    signer_weight INTEGER,
    data_name VARCHAR,
    data_value VARCHAR,
    host_function_type VARCHAR,
    parameters VARCHAR,
    address VARCHAR,
    contract_id VARCHAR,
    function_name VARCHAR,
    balance_id VARCHAR,
    claimant VARCHAR,
    claimant_muxed VARCHAR,
    predicate VARCHAR,
    liquidity_pool_id VARCHAR,
    reserve_a_asset VARCHAR,
    reserve_a_amount BIGINT,
    reserve_b_asset VARCHAR,
    reserve_b_amount BIGINT,
    shares BIGINT,
    shares_received BIGINT,
    into_account VARCHAR,
    into_muxed VARCHAR,
    sponsor VARCHAR,
    sponsored_id VARCHAR,
    begin_sponsor VARCHAR,
    tx_successful BOOLEAN,
    tx_fee_charged BIGINT,
    tx_max_fee BIGINT,
    tx_operation_count INTEGER,
    tx_memo_type VARCHAR,
    tx_memo VARCHAR,
    ledger_closed_at TIMESTAMP,
    ledger_total_coins BIGINT,
    ledger_fee_pool BIGINT,
    ledger_base_fee INTEGER,
    ledger_base_reserve INTEGER,
    ledger_transaction_count INTEGER,
    ledger_operation_count INTEGER,
    ledger_successful_tx_count INTEGER,
    ledger_failed_tx_count INTEGER,
    is_payment_op BOOLEAN,
    is_soroban_op BOOLEAN,
    inserted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.enriched_history_operations_soroban (
    transaction_hash VARCHAR,
    operation_index INTEGER,
    ledger_sequence BIGINT,
    source_account VARCHAR,
    type INTEGER,
    type_string VARCHAR,
    created_at TIMESTAMP,
    transaction_successful BOOLEAN,
    operation_result_code VARCHAR,
    operation_trace_code VARCHAR,
    ledger_range BIGINT,
    source_account_muxed VARCHAR,
    asset VARCHAR,
    asset_type VARCHAR,
    asset_code VARCHAR,
    asset_issuer VARCHAR,
    source_asset VARCHAR,
    source_asset_type VARCHAR,
    source_asset_code VARCHAR,
    source_asset_issuer VARCHAR,
    destination VARCHAR,
    destination_muxed VARCHAR,
    amount BIGINT,
    source_amount BIGINT,
    from_account VARCHAR,
    from_muxed VARCHAR,
    to_address VARCHAR,
    to_muxed VARCHAR,
    limit_amount BIGINT,
    offer_id BIGINT,
    selling_asset VARCHAR,
    selling_asset_type VARCHAR,
    selling_asset_code VARCHAR,
    selling_asset_issuer VARCHAR,
    buying_asset VARCHAR,
    buying_asset_type VARCHAR,
    buying_asset_code VARCHAR,
    buying_asset_issuer VARCHAR,
    price_n INTEGER,
    price_d INTEGER,
    price DECIMAL,
    starting_balance BIGINT,
    home_domain VARCHAR,
    inflation_dest VARCHAR,
    set_flags INTEGER,
    set_flags_s VARCHAR,
    clear_flags INTEGER,
    clear_flags_s VARCHAR,
    master_key_weight INTEGER,
    low_threshold INTEGER,
    med_threshold INTEGER,
    high_threshold INTEGER,
    signer_account_id VARCHAR,
    signer_key VARCHAR,
    signer_weight INTEGER,
    data_name VARCHAR,
    data_value VARCHAR,
    host_function_type VARCHAR,
    parameters VARCHAR,
    address VARCHAR,
    contract_id VARCHAR,
    function_name VARCHAR,
    balance_id VARCHAR,
    claimant VARCHAR,
    claimant_muxed VARCHAR,
    predicate VARCHAR,
    liquidity_pool_id VARCHAR,
    reserve_a_asset VARCHAR,
    reserve_a_amount BIGINT,
    reserve_b_asset VARCHAR,
    reserve_b_amount BIGINT,
    shares BIGINT,
    shares_received BIGINT,
    into_account VARCHAR,
    into_muxed VARCHAR,
    sponsor VARCHAR,
    sponsored_id VARCHAR,
    begin_sponsor VARCHAR,
    tx_successful BOOLEAN,
    tx_fee_charged BIGINT,
    tx_max_fee BIGINT,
    tx_operation_count INTEGER,
    tx_memo_type VARCHAR,
    tx_memo VARCHAR,
    ledger_closed_at TIMESTAMP,
    ledger_total_coins BIGINT,
    ledger_fee_pool BIGINT,
    ledger_base_fee INTEGER,
    ledger_base_reserve INTEGER,
    ledger_transaction_count INTEGER,
    ledger_operation_count INTEGER,
    ledger_successful_tx_count INTEGER,
    ledger_failed_tx_count INTEGER,
    is_payment_op BOOLEAN,
    is_soroban_op BOOLEAN,
    inserted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.offers_current (
    offer_id BIGINT,
    seller_id VARCHAR,
    selling_asset_type VARCHAR,
    selling_asset_code VARCHAR,
    selling_asset_issuer VARCHAR,
    buying_asset_type VARCHAR,
    buying_asset_code VARCHAR,
    buying_asset_issuer VARCHAR,
    amount BIGINT,
    price_n INTEGER,
    price_d INTEGER,
    price DECIMAL,
    flags INTEGER,
    last_modified_ledger BIGINT,
    ledger_sequence BIGINT,
    created_at TIMESTAMP,
    sponsor VARCHAR,
    ledger_range BIGINT,
    inserted_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.offers_snapshot (
    offer_id BIGINT,
    seller_account VARCHAR,
    ledger_sequence BIGINT,
    closed_at TIMESTAMP,
    selling_asset_type VARCHAR,
    selling_asset_code VARCHAR,
    selling_asset_issuer VARCHAR,
    buying_asset_type VARCHAR,
    buying_asset_code VARCHAR,
    buying_asset_issuer VARCHAR,
    amount VARCHAR,
    price VARCHAR,
    flags INTEGER,
    created_at TIMESTAMP,
    ledger_range BIGINT,
    era_id VARCHAR,
    version_label VARCHAR,
    valid_to TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.token_transfers_raw (
    timestamp TIMESTAMP,
    transaction_hash VARCHAR,
    ledger_sequence BIGINT,
    source_type VARCHAR,
    from_account VARCHAR,
    to_account VARCHAR,
    asset_code VARCHAR,
    asset_issuer VARCHAR,
    amount NUMERIC,
    token_contract_id VARCHAR,
    operation_type INTEGER,
    transaction_successful BOOLEAN,
    event_index INTEGER,
    inserted_at TIMESTAMP,
    ledger_range BIGINT
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.trustlines_current (
    account_id VARCHAR,
    asset_type VARCHAR,
    asset_issuer VARCHAR,
    asset_code VARCHAR,
    liquidity_pool_id VARCHAR,
    balance BIGINT,
    trust_line_limit BIGINT,
    buying_liabilities BIGINT,
    selling_liabilities BIGINT,
    flags INTEGER,
    last_modified_ledger BIGINT,
    ledger_sequence BIGINT,
    created_at TIMESTAMP,
    sponsor VARCHAR,
    ledger_range BIGINT,
    inserted_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.trustlines_snapshot (
    account_id VARCHAR,
    asset_code VARCHAR,
    asset_issuer VARCHAR,
    asset_type VARCHAR,
    balance VARCHAR,
    trust_limit VARCHAR,
    buying_liabilities VARCHAR,
    selling_liabilities VARCHAR,
    authorized BOOLEAN,
    authorized_to_maintain_liabilities BOOLEAN,
    clawback_enabled BOOLEAN,
    ledger_sequence BIGINT,
    created_at TIMESTAMP,
    ledger_range BIGINT,
    era_id VARCHAR,
    version_label VARCHAR,
    valid_to TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.contract_invocations_raw (
    ledger_sequence BIGINT,
    transaction_index INTEGER,
    operation_index INTEGER,
    transaction_hash VARCHAR,
    source_account VARCHAR,
    contract_id VARCHAR,
    function_name VARCHAR,
    arguments_json TEXT,
    successful BOOLEAN,
    closed_at TIMESTAMP,
    ledger_range BIGINT,
    inserted_at TIMESTAMP,
    era_id VARCHAR,
    version_label VARCHAR
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.contract_metadata (
    contract_id VARCHAR,
    creator_address VARCHAR,
    wasm_hash VARCHAR,
    created_ledger BIGINT,
    created_at TIMESTAMP,
    inserted_at TIMESTAMP,
    era_id VARCHAR,
    version_label VARCHAR
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.semantic_activities (
    id VARCHAR,
    ledger_sequence BIGINT,
    timestamp TIMESTAMP,
    activity_type VARCHAR,
    description VARCHAR,
    source_account VARCHAR,
    destination_account VARCHAR,
    contract_id VARCHAR,
    asset_code VARCHAR,
    asset_issuer VARCHAR,
    amount VARCHAR,
    is_soroban BOOLEAN,
    soroban_function_name VARCHAR,
    transaction_hash VARCHAR,
    operation_index INTEGER,
    successful BOOLEAN,
    fee_charged BIGINT,
    created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.semantic_entities_contracts (
    contract_id VARCHAR,
    contract_type VARCHAR,
    token_name VARCHAR,
    token_symbol VARCHAR,
    token_decimals INTEGER,
    deployer_account VARCHAR,
    deployed_at TIMESTAMP,
    deployed_ledger BIGINT,
    total_invocations BIGINT,
    last_activity TIMESTAMP,
    unique_callers BIGINT,
    observed_functions VARCHAR,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.semantic_flows_value (
    id VARCHAR,
    ledger_sequence BIGINT,
    timestamp TIMESTAMP,
    flow_type VARCHAR,
    from_account VARCHAR,
    to_account VARCHAR,
    contract_id VARCHAR,
    asset_code VARCHAR,
    asset_issuer VARCHAR,
    asset_type VARCHAR,
    amount VARCHAR,
    transaction_hash VARCHAR,
    operation_type INTEGER,
    successful BOOLEAN,
    created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.semantic_contract_functions (
    contract_id VARCHAR,
    function_name VARCHAR,
    total_calls BIGINT,
    successful_calls BIGINT,
    failed_calls BIGINT,
    unique_callers BIGINT,
    first_called TIMESTAMP,
    last_called TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.semantic_asset_stats (
    asset_key VARCHAR,
    asset_code VARCHAR,
    asset_issuer VARCHAR,
    asset_type VARCHAR,
    token_name VARCHAR,
    token_symbol VARCHAR,
    token_decimals INTEGER,
    contract_id VARCHAR,
    holder_count BIGINT,
    transfer_count_24h BIGINT,
    transfer_volume_24h DECIMAL,
    transfer_count_7d BIGINT,
    transfer_volume_7d DECIMAL,
    mint_count_24h BIGINT,
    burn_count_24h BIGINT,
    first_seen TIMESTAMP,
    last_transfer TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.semantic_dex_pairs (
    pair_key VARCHAR,
    selling_asset_code VARCHAR,
    selling_asset_issuer VARCHAR,
    buying_asset_code VARCHAR,
    buying_asset_issuer VARCHAR,
    trade_count BIGINT,
    trade_count_24h BIGINT,
    trade_count_7d BIGINT,
    selling_volume DECIMAL,
    buying_volume DECIMAL,
    selling_volume_24h DECIMAL,
    buying_volume_24h DECIMAL,
    last_price DECIMAL,
    unique_sellers BIGINT,
    unique_buyers BIGINT,
    first_trade TIMESTAMP,
    last_trade TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testnet_catalog.silver.semantic_account_summary (
    account_id VARCHAR,
    total_operations BIGINT,
    total_payments_sent BIGINT,
    total_payments_received BIGINT,
    total_contract_calls BIGINT,
    unique_contracts_called BIGINT,
    top_contract_id VARCHAR,
    top_contract_function VARCHAR,
    is_contract_deployer BOOLEAN,
    contracts_deployed INTEGER,
    first_activity TIMESTAMP,
    last_activity TIMESTAMP,
    updated_at TIMESTAMP
);

