-- DuckLake Bronze Schema - Full Hubble-compatible definitions
-- Matches PostgreSQL hot buffer schema exactly for seamless flush
-- Generated to align with postgres-hot-buffer migrations

-- ============================================================================
-- CORE TABLES (ledgers, transactions, operations)
-- ============================================================================

CREATE TABLE IF NOT EXISTS bronze.ledgers_row_v2 (
    sequence BIGINT,
    ledger_hash TEXT,
    previous_ledger_hash TEXT,
    closed_at TIMESTAMP,
    protocol_version INTEGER,
    total_coins BIGINT,
    fee_pool BIGINT,
    base_fee INTEGER,
    base_reserve INTEGER,
    max_tx_set_size INTEGER,
    successful_tx_count INTEGER,
    failed_tx_count INTEGER,
    ingestion_timestamp TIMESTAMP,
    ledger_range BIGINT,
    transaction_count INTEGER,
    operation_count INTEGER,
    tx_set_operation_count INTEGER,
    soroban_fee_write1kb BIGINT,
    node_id TEXT,
    signature TEXT,
    ledger_header TEXT,
    bucket_list_size BIGINT,
    live_soroban_state_size BIGINT,
    evicted_keys_count INTEGER,
    era_id TEXT,
    version_label TEXT
);

CREATE TABLE IF NOT EXISTS bronze.transactions_row_v2 (
    ledger_sequence BIGINT,
    transaction_hash TEXT,
    source_account TEXT,
    fee_charged BIGINT,
    max_fee BIGINT,
    successful BOOLEAN,
    transaction_result_code TEXT,
    operation_count INTEGER,
    memo_type TEXT,
    memo TEXT,
    created_at TIMESTAMP,
    account_sequence BIGINT,
    ledger_range BIGINT,
    source_account_muxed TEXT,
    fee_account_muxed TEXT,
    inner_transaction_hash TEXT,
    fee_bump_fee BIGINT,
    max_fee_bid BIGINT,
    inner_source_account TEXT,
    timebounds_min_time BIGINT,
    timebounds_max_time BIGINT,
    ledgerbounds_min BIGINT,
    ledgerbounds_max BIGINT,
    min_sequence_number BIGINT,
    min_sequence_age BIGINT,
    soroban_resources_instructions BIGINT,
    soroban_resources_read_bytes BIGINT,
    soroban_resources_write_bytes BIGINT,
    soroban_data_size_bytes INTEGER,
    soroban_data_resources TEXT,
    soroban_fee_base BIGINT,
    soroban_fee_resources BIGINT,
    soroban_fee_refund BIGINT,
    soroban_fee_charged BIGINT,
    soroban_fee_wasted BIGINT,
    soroban_host_function_type TEXT,
    soroban_contract_id TEXT,
    soroban_contract_events_count INTEGER,
    signatures_count INTEGER,
    new_account BOOLEAN,
    tx_envelope TEXT,
    tx_result TEXT,
    tx_meta TEXT,
    tx_fee_meta TEXT,
    tx_signers TEXT,
    extra_signers TEXT,
    era_id TEXT,
    version_label TEXT
);

CREATE TABLE IF NOT EXISTS bronze.operations_row_v2 (
    transaction_hash TEXT,
    operation_index INTEGER,
    ledger_sequence BIGINT,
    source_account TEXT,
    type INTEGER,
    type_string TEXT,
    created_at TIMESTAMP,
    transaction_successful BOOLEAN,
    operation_result_code TEXT,
    operation_trace_code TEXT,
    ledger_range BIGINT,
    source_account_muxed TEXT,
    asset TEXT,
    asset_type TEXT,
    asset_code TEXT,
    asset_issuer TEXT,
    source_asset TEXT,
    source_asset_type TEXT,
    source_asset_code TEXT,
    source_asset_issuer TEXT,
    amount BIGINT,
    source_amount BIGINT,
    destination_min BIGINT,
    starting_balance BIGINT,
    destination TEXT,
    trustline_limit BIGINT,
    trustor TEXT,
    authorize BOOLEAN,
    authorize_to_maintain_liabilities BOOLEAN,
    trust_line_flags INTEGER,
    balance_id TEXT,
    claimants_count INTEGER,
    sponsored_id TEXT,
    offer_id BIGINT,
    price TEXT,
    price_r TEXT,
    buying_asset TEXT,
    buying_asset_type TEXT,
    buying_asset_code TEXT,
    buying_asset_issuer TEXT,
    selling_asset TEXT,
    selling_asset_type TEXT,
    selling_asset_code TEXT,
    selling_asset_issuer TEXT,
    soroban_operation TEXT,
    soroban_function TEXT,
    soroban_contract_id TEXT,
    soroban_auth_required BOOLEAN,
    bump_to BIGINT,
    set_flags INTEGER,
    clear_flags INTEGER,
    home_domain TEXT,
    master_weight INTEGER,
    low_threshold INTEGER,
    medium_threshold INTEGER,
    high_threshold INTEGER,
    data_name TEXT,
    data_value TEXT,
    era_id TEXT,
    version_label TEXT
);

-- ============================================================================
-- EFFECTS AND TRADES
-- ============================================================================

CREATE TABLE IF NOT EXISTS bronze.effects_row_v1 (
    ledger_sequence BIGINT,
    transaction_hash TEXT,
    operation_index INTEGER,
    effect_index INTEGER,
    effect_type INTEGER,
    effect_type_string TEXT,
    account TEXT,
    account_muxed TEXT,
    amount BIGINT,
    asset_type TEXT,
    asset_code TEXT,
    asset_issuer TEXT,
    source_asset_type TEXT,
    source_asset_code TEXT,
    source_asset_issuer TEXT,
    signer_account TEXT,
    signer_weight INTEGER,
    created_at TIMESTAMP,
    ledger_range BIGINT,
    era_id TEXT,
    version_label TEXT
);

CREATE TABLE IF NOT EXISTS bronze.trades_row_v1 (
    ledger_sequence BIGINT,
    offer_id BIGINT,
    base_offer_id BIGINT,
    base_account TEXT,
    base_asset_type TEXT,
    base_asset_code TEXT,
    base_asset_issuer TEXT,
    base_amount BIGINT,
    counter_offer_id BIGINT,
    counter_account TEXT,
    counter_asset_type TEXT,
    counter_asset_code TEXT,
    counter_asset_issuer TEXT,
    counter_amount BIGINT,
    price_n BIGINT,
    price_d BIGINT,
    created_at TIMESTAMP,
    ledger_range BIGINT,
    era_id TEXT,
    version_label TEXT
);

-- Continued in next message due to length...
