# DuckLake Ingestion Processor - Local DuckDB Catalog Test
# Test performance with local catalog to isolate network latency

service:
  name: "ducklake-ingestion-processor"
  environment: "development"

# Stellar data source
source:
  endpoint: "localhost:50053"  # stellar-live-source-datalake default port
  network_passphrase: "Test SDF Network ; September 2015"
  start_ledger: 503000
  end_ledger: 505000  # Test COPY FROM with 2000 ledgers for batch testing

# DuckLake configuration (LOCAL DuckDB catalog + local filesystem storage)
ducklake:
  # LOCAL DuckDB catalog (no network latency)
  catalog_path: "ducklake:duckdb:./test_local_catalog.db"

  # Local filesystem storage (no B2 network latency)
  data_path: "./test_local_data"

  # Catalog and schema names
  catalog_name: "local_test"
  schema_name: "ledgers"

  # Table configuration
  table_name: "ledgers"

  # B2 credentials (not needed for local, but keeping for compatibility)
  aws_access_key_id: ""
  aws_secret_access_key: ""
  aws_region: ""
  aws_endpoint: ""

  # Public archive settings
  enable_public_archive: false

  # Performance settings
  batch_size: 500  # Test COPY FROM with 500 ledgers per batch
  commit_interval_seconds: 30
  use_upsert: false
  create_indexes: false

# Logging
logging:
  level: "info"
  format: "console"
